config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :image_conmments
  resources :images

  devise_for :users
  resources :books

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
    mount_uploader :file ,ImageUploader
    belongs_to :user
    has_many :image_comment, -> {order "created_at DESC"}
end

app/models/image_conmment.rb
class ImageConmment < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name,presence: true
  validates :age,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up, key: [:name, :age]
    devise_parameter_sanitizer.permit :account_update, key: [:name, :age]
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :number_of_pages)
    end
end

app/controllers/image_conmments_controller.rb
class ImageConmmentsController < ApplicationController
  before_action :set_image_conmment, only: [:show, :edit, :update, :destroy]

  # GET /image_conmments
  # GET /image_conmments.json
  def index
    @image_conmments = ImageConmment.all
  end

  # GET /image_conmments/1
  # GET /image_conmments/1.json
  def show
  end

  # GET /image_conmments/new
  def new
    @image_conmment = ImageConmment.new
  end

  # GET /image_conmments/1/edit
  def edit
  end

  # POST /image_conmments
  # POST /image_conmments.json
  def create
    @image_conmment = ImageConmment.new(image_conmment_params)
    @iamge_comment.user_id = current_user.id

    respond_to do |format|
      if @image_conmment.save
        url= "/images" + @image_conmment.image_id.to_s
        format.html { redirect_to url, notice: 'Image conmment was successfully created.' }
        format.json { render :show, status: :created, location: @image_conmment }
      else
        format.html { render :new }
        format.json { render json: @image_conmment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_conmments/1
  # PATCH/PUT /image_conmments/1.json
  def update
    respond_to do |format|
      if @image_conmment.update(image_conmment_params)
        format.html { redirect_to @image_conmment, notice: 'Image conmment was successfully updated.' }
        format.json { render :show, status: :ok, location: @image_conmment }
      else
        format.html { render :edit }
        format.json { render json: @image_conmment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_conmments/1
  # DELETE /image_conmments/1.json
  def destroy
    @image_conmment.destroy
    respond_to do |format|
      format.html { redirect_to image_conmments_url, notice: 'Image conmment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_conmment
      @image_conmment = ImageConmment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_conmment_params
      params.require(:image_conmment).permit(:user_id, :image_id, :comment)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
    @image_comment = ImageConmment.new
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    @image.user_id=current_user.id

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:user_id, :title, :file, :created_at)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/image_conmments_helper.rb
module ImageConmmentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :number_of_pages %><br>
    <%= f.number_field :number_of_pages %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Number of pages</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.number_of_pages %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Number of pages:</strong>
  <%= @book.number_of_pages %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/image_conmments/_form.html.erb
<%= form_for(@image_conmment) do |f| %>
  <% if @image_conmment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image_conmment.errors.count, "error") %> prohibited this image_conmment from being saved:</h2>

      <ul>
      <% @image_conmment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :image_id %><br>
    <%= f.number_field :image_id %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/image_conmments/edit.html.erb
<h1>Editing Image Conmment</h1>

<%= render 'form' %>

<%= link_to 'Show', @image_conmment %> |
<%= link_to 'Back', image_conmments_path %>

app/views/image_conmments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Image Conmments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Image</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @image_conmments.each do |image_conmment| %>
      <tr>
        <td><%= image_conmment.user_id %></td>
        <td><%= image_conmment.image_id %></td>
        <td><%= image_conmment.comment %></td>
        <td><%= link_to 'Show', image_conmment %></td>
        <td><%= link_to 'Edit', edit_image_conmment_path(image_conmment) %></td>
        <td><%= link_to 'Destroy', image_conmment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image conmment', new_image_conmment_path %>

app/views/image_conmments/new.html.erb
<h1>New Image Conmment</h1>

<%= render 'form' %>

<%= link_to 'Back', image_conmments_path %>

app/views/image_conmments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @image_conmment.user_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @image_conmment.image_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @image_conmment.comment %>
</p>

<%= link_to 'Edit', edit_image_conmment_path(@image_conmment) %> |
<%= link_to 'Back', image_conmments_path %>

app/views/images/_form.html.erb
<%= form_for(@image, {multipart: true}) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label 'image' %><br>
    <%= f.text_field :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>File</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.user_id %></td>
        <td><%= image.title %></td>
        <td><%= image.file %></td>
        <td><%= image.created_at %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @image.user.email %>
</p>

<p>
  <strong>Title:</strong>
  <%= @image.title %>
</p>

<p>
  <strong>File:</strong>
  <%= image_tag @image.file %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @image.created_at %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>
<h2> comment </h2>
<%= form_for(@image_comment) do |f| %>
<div class= "field">
  <%= f.label :comment %> <br>
  <%= f.text_field :comment %>
  <%= f.hidden_field :image_id, :value => @image.id%>
</div>
  <div class= "action">
  <%= f.submit %>
  </div>
  <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <h3>hello <%= current_user.email %></h3><hr>
  <%= link_to "log out", destroy_user_session_path,method: :delete %>
  <%= yield %>
<% else %>
  <%= link_to "sign in", new_user_session_path %>
  <%= link_to "sign up", new_user_registration_path %>
<% end %>
<%=yield%>
</body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>